"""Configuration settings for SAP CPI Specification Generator."""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base paths
BASE_DIR = Path(__file__).parent.parent
OUTPUT_DIR = BASE_DIR / "output"
TEMP_DIR = BASE_DIR / "temp"

# Ensure directories exist
OUTPUT_DIR.mkdir(exist_ok=True)
TEMP_DIR.mkdir(exist_ok=True)

# AI Configuration
AI_MODEL = os.getenv("AI_MODEL", "gemini-2.0-flash")
AI_MODEL_THINKING = os.getenv("AI_MODEL_THINKING", "gemini-2.0-flash-thinking-exp-01-21")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Feature toggles
ENABLE_AI_SUMMARIES = os.getenv("ENABLE_AI_SUMMARIES", "true").lower() == "true"
ENABLE_AI_CACHING = os.getenv("ENABLE_AI_CACHING", "true").lower() == "true"
ENABLE_BATCH_MODE = os.getenv("ENABLE_BATCH_MODE", "true").lower() == "true"
ENABLE_STREAMING = os.getenv("ENABLE_STREAMING", "false").lower() == "true"
USE_THINKING_MODEL = os.getenv("USE_THINKING_MODEL", "false").lower() == "true"

# Document settings
DOC_AUTHOR = os.getenv("DOC_AUTHOR", "Generated by AI")
DOC_VERSION = os.getenv("DOC_VERSION", "1.0")

# AI settings
AI_MAX_RETRIES = int(os.getenv("AI_MAX_RETRIES", "3"))
AI_TIMEOUT_SECONDS = int(os.getenv("AI_TIMEOUT_SECONDS", "60"))
AI_SENTENCE_LIMIT = int(os.getenv("AI_SENTENCE_LIMIT", "5"))
FUNCTIONAL_SPEC_MAX_CHARS = int(os.getenv("FUNCTIONAL_SPEC_MAX_CHARS", "15000"))


def validate_config() -> tuple[bool, list[str]]:
    """Validate configuration and return (is_valid, error_messages)."""
    errors = []
    
    if not GEMINI_API_KEY:
        errors.append("GEMINI_API_KEY is not set. Set it in .env file or environment.")
    
    if not AI_MODEL:
        errors.append("AI_MODEL is not configured.")
    
    if not OUTPUT_DIR.exists():
        try:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            errors.append(f"Cannot create output directory: {e}")
    
    if not TEMP_DIR.exists():
        try:
            TEMP_DIR.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            errors.append(f"Cannot create temp directory: {e}")
    
    return len(errors) == 0, errors


def print_config():
    """Print current configuration (for debugging)."""
    print(f"Configuration:")
    print(f"  BASE_DIR: {BASE_DIR}")
    print(f"  OUTPUT_DIR: {OUTPUT_DIR}")
    print(f"  TEMP_DIR: {TEMP_DIR}")
    print(f"  AI_MODEL: {AI_MODEL}")
    print(f"  AI_MODEL_THINKING: {AI_MODEL_THINKING}")
    print(f"  API_KEY: {'Set' if GEMINI_API_KEY else 'NOT SET'}")
    print(f"  AI_SUMMARIES: {ENABLE_AI_SUMMARIES}")
    print(f"  AI_CACHING: {ENABLE_AI_CACHING}")
    print(f"  BATCH_MODE: {ENABLE_BATCH_MODE}")
    print(f"  STREAMING: {ENABLE_STREAMING}")
    print(f"  USE_THINKING_MODEL: {USE_THINKING_MODEL}")
    print(f"  DOC_AUTHOR: {DOC_AUTHOR}")
    print(f"  DOC_VERSION: {DOC_VERSION}")
    print(f"  FUNCTIONAL_SPEC_MAX_CHARS: {FUNCTIONAL_SPEC_MAX_CHARS}")
