"""Configuration settings for SAP CPI Specification Generator."""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base paths
BASE_DIR = Path(__file__).parent.parent
OUTPUT_DIR = BASE_DIR / "output"
TEMP_DIR = BASE_DIR / "temp"

# Ensure directories exist
OUTPUT_DIR.mkdir(exist_ok=True)
TEMP_DIR.mkdir(exist_ok=True)

CONFIG_WARNINGS: list[str] = []


def _get_int_env(name: str, default: int, minimum: int | None = None) -> int:
    """Read integer environment variables without failing during module import."""
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == "":
        value = default
    else:
        try:
            value = int(str(raw).strip())
        except ValueError:
            CONFIG_WARNINGS.append(f"{name} must be an integer; using default {default}.")
            value = default

    if minimum is not None and value < minimum:
        CONFIG_WARNINGS.append(f"{name} must be >= {minimum}; using default {default}.")
        value = default
    return value

# AI Configuration
AI_MODEL = os.getenv("AI_MODEL", "gemini-2.0-flash")
AI_MODEL_THINKING = os.getenv("AI_MODEL_THINKING", "gemini-2.0-flash-thinking-exp-01-21")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Feature toggles
ENABLE_AI_SUMMARIES = os.getenv("ENABLE_AI_SUMMARIES", "true").lower() == "true"
ENABLE_AI_CACHING = os.getenv("ENABLE_AI_CACHING", "true").lower() == "true"
ENABLE_BATCH_MODE = os.getenv("ENABLE_BATCH_MODE", "true").lower() == "true"
ENABLE_STREAMING = os.getenv("ENABLE_STREAMING", "false").lower() == "true"
USE_THINKING_MODEL = os.getenv("USE_THINKING_MODEL", "false").lower() == "true"

# Document settings
DOC_AUTHOR = os.getenv("DOC_AUTHOR", "Generated by AI")
DOC_VERSION = os.getenv("DOC_VERSION", "1.0")
TECH_SPEC_SCOPE_MODE = os.getenv("TECH_SPEC_SCOPE_MODE", "strict").strip().lower()

# AI settings
AI_MAX_RETRIES = _get_int_env("AI_MAX_RETRIES", 3, minimum=1)
AI_TIMEOUT_SECONDS = _get_int_env("AI_TIMEOUT_SECONDS", 60, minimum=1)
AI_SENTENCE_LIMIT = _get_int_env("AI_SENTENCE_LIMIT", 5, minimum=1)
FUNCTIONAL_SPEC_MAX_CHARS = _get_int_env("FUNCTIONAL_SPEC_MAX_CHARS", 15000, minimum=0)


def validate_config() -> tuple[bool, list[str]]:
    """Validate configuration and return (is_valid, error_messages)."""
    errors = []
    
    if not GEMINI_API_KEY:
        errors.append("GEMINI_API_KEY is not set. Set it in .env file or environment.")
    
    if not AI_MODEL:
        errors.append("AI_MODEL is not configured.")

    if TECH_SPEC_SCOPE_MODE not in {"strict", "extended"}:
        errors.append(
            "TECH_SPEC_SCOPE_MODE must be either 'strict' or 'extended'."
        )

    errors.extend(CONFIG_WARNINGS)
    
    if not OUTPUT_DIR.exists():
        try:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            errors.append(f"Cannot create output directory: {e}")
    
    if not TEMP_DIR.exists():
        try:
            TEMP_DIR.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            errors.append(f"Cannot create temp directory: {e}")
    
    return len(errors) == 0, errors


def print_config():
    """Print current configuration (for debugging)."""
    print(f"Configuration:")
    print(f"  BASE_DIR: {BASE_DIR}")
    print(f"  OUTPUT_DIR: {OUTPUT_DIR}")
    print(f"  TEMP_DIR: {TEMP_DIR}")
    print(f"  AI_MODEL: {AI_MODEL}")
    print(f"  AI_MODEL_THINKING: {AI_MODEL_THINKING}")
    print(f"  API_KEY: {'Set' if GEMINI_API_KEY else 'NOT SET'}")
    print(f"  AI_SUMMARIES: {ENABLE_AI_SUMMARIES}")
    print(f"  AI_CACHING: {ENABLE_AI_CACHING}")
    print(f"  BATCH_MODE: {ENABLE_BATCH_MODE}")
    print(f"  STREAMING: {ENABLE_STREAMING}")
    print(f"  USE_THINKING_MODEL: {USE_THINKING_MODEL}")
    print(f"  DOC_AUTHOR: {DOC_AUTHOR}")
    print(f"  DOC_VERSION: {DOC_VERSION}")
    print(f"  TECH_SPEC_SCOPE_MODE: {TECH_SPEC_SCOPE_MODE}")
    print(f"  FUNCTIONAL_SPEC_MAX_CHARS: {FUNCTIONAL_SPEC_MAX_CHARS}")
